---
title: "**Presentations in R with revealjs**"
author: "*Roberto Jesús Alcaraz Molina*"
date: "26/02/2021"
output: 
  revealjs::revealjs_presentation:
    theme: serif
    highlight: kate
    transition: convex
    css: styles.css
    reveal_options:
      slideNumber: true
---

# Stat2Data data set

In the following presentation we will do a simple analysis of the ``ThreeCars`` data set from the ``Stat2Data`` package.

```{r, echo=F}
pacman::p_load(Stat2Data, knitr, plotly, dplyr, patchwork, ggplot2)
# install_github("thomasp85/patchwork")
```

```{r, echo=F}
data("ThreeCars")
kable(head(ThreeCars), caption = "First five observations in the data")
```

## Summary of the the categorical variables

```{r, echo=F}
# 
```

## Summary of the the numerical variables

```{r, echo=F}
bw1 = ks::hpi(ThreeCars$Price)
p1 = ggplot(data = ThreeCars, aes(x = Price)) +
  geom_histogram(binwidth = bw1, fill = "white", color = "black") +
  theme_bw()

bw2 = ks::hpi(ThreeCars$Age)
p2 = ggplot(data = ThreeCars, aes(x = Age)) +
  geom_histogram(binwidth = bw2, fill = "white", color = "black") +
  theme_bw()

p1 + p2
```



